require.config({
    paths: {
        'Detector':'cloud/Detector',
        'THREE':'cloud/three.min',
        'cloud':'cloud',
        'marked':'marked',
        'prism':'prism',
        'pubu':'pubu',
        'utils':'utils'
    },
    shim:{
        'pubu':{
            exports:'pubu'
        },
        'cloud':{
            deps:['Detector','THREE'],
            exports:'cloud'
        }    
    }
});
